(ns borges.const)

(defonce ^:const erlang-term 131)
(defonce ^:const erlang-small-integer 97)
(defonce ^:const erlang-integer 98)
(defonce ^:const erlang-float 99)
(defonce ^:const erlang-new-float 70)
(defonce ^:const erlang-atom 100)
(defonce ^:const erlang-small-tuple 104)
(defonce ^:const erlang-large-tuple 105)
(defonce ^:const erlang-nil 106)
(defonce ^:const erlang-string 107)
(defonce ^:const erlang-list 108)
(defonce ^:const erlang-small-bignum 110)
(defonce ^:const erlang-large-bignum 111)
(defonce ^:const erlang-new-reference 114)
(defonce ^:const erlang-pid 103)
(defonce ^:const erlang-map 116)
(defonce ^:const erlang-binary 109)
